### ISSUE TITLE
TODO v1.*

### ISSUE THREAD

**Issue by tanatarca** [aravergar/IG#1]
Estructuras de clase para:
- Tetraedro
- Cubo
- Cilindro
- Cono
- Toro
- Esfera
- Whatever

Visualización en modos:
- Vértices
- Alambre
- Sólido
- Ajedrez

**Comment by aravergar** [comment]
Estructuras de clase:
* Clase para Objeto 3D abstracta (con funciones _pure virtual_ como *Draw* o constructores)
* Clases para cada _clase_ de objeto.
  * Prisma (Cubo, cilindro...)
  * Pirámide (Tetraedro, demás pirámides, conos...)
  * Esfera (por ahora, sólo esferas perfectas dado parámetro)
  * Toro (dados sus dos parámetros)
* Estructuras para almacenar los _mesh_ (tentativamente, sistema de representación por _semiaristas aladas_):
  * Vértices
  * Semiaristas
  * Caras

**Comment by tanatarca** [comment]
Primera parte tratada en #2
