### ISSUE TITLE
TODO Elección de eje

### ISSUE THREAD

**Issue by tanatarca** [aravergar/IG#12]
**Elección de eje** - posibilitar la elección del eje alrededor del cual revolucionar el perfil (entre los dos posibles en cada caso). Implementar reconocimiento de plano

**Comment by tanatarca** [comment]
Hay que cambiar el constructor para poder elegir el eje de rotación

**Comment by aravergar** [comment]
Pasada a #11

**Comment by tanatarca** [comment]
Pasada a #11 como parte de su especificación
