### ISSUE TITLE
TODO Interacción

### ISSUE THREAD

**Issue by tanatarca** [aravergar/IG#5]
Interacción y eventos para cargar los diferentes objetos y activar los diferentes modos de visualización.

**Comment by tanatarca** [comment]
Ejemplo de asignación de teclas
- **1** - carga tetraedro
- **2** - carga cubo
- **3** - carga cono
- **4** - carga cilindro
- **¿5?** - carga toro

**Comment by aravergar** [comment]
4b89facc75b03c7c476f42cd7fff28a278f19453 closes #5

**Comment by tanatarca** [comment]
4b89facc75b03c7c476f42cd7fff28a278f19453 closes #5
